export interface ChapterVideo {
  chapterNumber: number; // 1 to 49
  volume: number; // 1 or 2
  volumeChapterNumber: number; // chapter number within the volume
  moduleId: string;
  day: string;
  videoTitle: string;
  videoUrl: string;
  embedUrl: string;
  playlistIndex?: number;
}

export const CHAPTER_VIDEOS: ChapterVideo[] = [
  // ==========================================
  // VOLUME 1: FUNDAMENTALS AND PROTOCOLS (1-24)
  // ==========================================
  {
    chapterNumber: 1,
    volume: 1,
    volumeChapterNumber: 1,
    moduleId: "v1-ch1-introduction-to-the-ccna",
    day: "Day 1",
    videoTitle: "Free CCNA | Network Devices | Day 1 | CCNA 200-301 Complete Course",
    videoUrl: "https://www.youtube.com/watch?v=H8W9oMNSuwo&list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ",
    embedUrl: "https://www.youtube-nocookie.com/embed/H8W9oMNSuwo?list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ",
    playlistIndex: 1,
  },
  {
    chapterNumber: 2,
    volume: 1,
    volumeChapterNumber: 2,
    moduleId: "v1-ch2-network-devices",
    day: "Day 2",
    videoTitle: "Free CCNA | Interfaces and Cables | Day 2 | CCNA 200-301 Complete Course",
    videoUrl: "https://www.youtube.com/watch?v=H8W9oMNSuwo&list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=4",
    embedUrl: "https://www.youtube-nocookie.com/embed/videoseries?list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=4",
    playlistIndex: 4,
  },
  {
    chapterNumber: 3,
    volume: 1,
    volumeChapterNumber: 3,
    moduleId: "v1-ch3-cables-connectors-and-ports",
    day: "Day 3",
    videoTitle: "Free CCNA | OSI Model & TCP/IP Suite | Day 3 | CCNA 200-301 Complete Course",
    videoUrl: "https://www.youtube.com/watch?v=H8W9oMNSuwo&list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=6",
    embedUrl: "https://www.youtube-nocookie.com/embed/videoseries?list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=6",
    playlistIndex: 6,
  },
  {
    chapterNumber: 4,
    volume: 1,
    volumeChapterNumber: 4,
    moduleId: "v1-ch4-the-tcp-ip-networking-model",
    day: "Day 4",
    videoTitle: "Free CCNA | Intro to the CLI | Day 4 | CCNA 200-301 Complete Course",
    videoUrl: "https://www.youtube.com/watch?v=H8W9oMNSuwo&list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=8",
    embedUrl: "https://www.youtube-nocookie.com/embed/videoseries?list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=8",
    playlistIndex: 8,
  },
  {
    chapterNumber: 5,
    volume: 1,
    volumeChapterNumber: 5,
    moduleId: "v1-ch5-the-cisco-ios-cli",
    day: "Day 5",
    videoTitle: "Free CCNA | Ethernet LAN Switching (Part 1) | Day 5 | CCNA 200-301 Complete Course",
    videoUrl: "https://www.youtube.com/watch?v=H8W9oMNSuwo&list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=10",
    embedUrl: "https://www.youtube-nocookie.com/embed/videoseries?list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=10",
    playlistIndex: 10,
  },
  {
    chapterNumber: 6,
    volume: 1,
    volumeChapterNumber: 6,
    moduleId: "v1-ch6-ethernet-lan-switching",
    day: "Day 6",
    videoTitle: "Free CCNA | Ethernet LAN Switching (Part 2) | Day 6 | CCNA 200-301 Complete Course",
    videoUrl: "https://www.youtube.com/watch?v=H8W9oMNSuwo&list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=11",
    embedUrl: "https://www.youtube-nocookie.com/embed/videoseries?list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=11",
    playlistIndex: 11,
  },
  {
    chapterNumber: 7,
    volume: 1,
    volumeChapterNumber: 7,
    moduleId: "v1-ch7-ipv4-addressing",
    day: "Day 7",
    videoTitle: "Free CCNA | IPv4 Addressing (Part 1) | Day 7 | CCNA 200-301 Complete Course",
    videoUrl: "https://www.youtube.com/watch?v=H8W9oMNSuwo&list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=13",
    embedUrl: "https://www.youtube-nocookie.com/embed/videoseries?list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=13",
    playlistIndex: 13,
  },
  {
    chapterNumber: 8,
    volume: 1,
    volumeChapterNumber: 8,
    moduleId: "v1-ch8-router-and-switch-interfaces",
    day: "Day 8",
    videoTitle: "Free CCNA | IPv4 Addressing (Part 2) | Day 8 | CCNA 200-301 Complete Course",
    videoUrl: "https://www.youtube.com/watch?v=H8W9oMNSuwo&list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=14",
    embedUrl: "https://www.youtube-nocookie.com/embed/videoseries?list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=14",
    playlistIndex: 14,
  },
  {
    chapterNumber: 9,
    volume: 1,
    volumeChapterNumber: 9,
    moduleId: "v1-ch9-routing-fundamentals",
    day: "Day 13-15",
    videoTitle: "Free CCNA | Subnetting (Part 1-3) | Day 13-15 | CCNA 200-301 Complete Course",
    videoUrl: "https://www.youtube.com/watch?v=H8W9oMNSuwo&list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=25",
    embedUrl: "https://www.youtube-nocookie.com/embed/videoseries?list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=25",
    playlistIndex: 25,
  },
  {
    chapterNumber: 10,
    volume: 1,
    volumeChapterNumber: 10,
    moduleId: "v1-ch10-the-life-of-a-packet",
    day: "Day 16",
    videoTitle: "Free CCNA | VLSM | Day 16 | CCNA 200-301 Complete Course",
    videoUrl: "https://www.youtube.com/watch?v=H8W9oMNSuwo&list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=29",
    embedUrl: "https://www.youtube-nocookie.com/embed/videoseries?list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=29",
    playlistIndex: 29,
  },
  {
    chapterNumber: 11,
    volume: 1,
    volumeChapterNumber: 11,
    moduleId: "v1-ch11-subnetting-ipv4-networks",
    day: "Day 11",
    videoTitle: "Free CCNA | Static Routing | Day 11 | CCNA 200-301 Complete Course",
    videoUrl: "https://www.youtube.com/watch?v=H8W9oMNSuwo&list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=20",
    embedUrl: "https://www.youtube-nocookie.com/embed/videoseries?list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=20",
    playlistIndex: 20,
  },
  {
    chapterNumber: 12,
    volume: 1,
    volumeChapterNumber: 12,
    moduleId: "v1-ch12-vlans",
    day: "Day 17-18",
    videoTitle: "Free CCNA | VLANs (Part 1 & 2) | Day 17-18 | CCNA 200-301 Complete Course",
    videoUrl: "https://www.youtube.com/watch?v=H8W9oMNSuwo&list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=31",
    embedUrl: "https://www.youtube-nocookie.com/embed/videoseries?list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=31",
    playlistIndex: 31,
  },
  {
    chapterNumber: 13,
    volume: 1,
    volumeChapterNumber: 13,
    moduleId: "v1-ch13-dynamic-trunking-protocol-and-vlan-trunking-protocol",
    day: "Day 19",
    videoTitle: "Free CCNA | DTP & VTP | Day 19 | CCNA 200-301 Complete Course",
    videoUrl: "https://www.youtube.com/watch?v=H8W9oMNSuwo&list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=34",
    embedUrl: "https://www.youtube-nocookie.com/embed/videoseries?list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=34",
    playlistIndex: 34,
  },
  {
    chapterNumber: 14,
    volume: 1,
    volumeChapterNumber: 14,
    moduleId: "v1-ch14-spanning-tree-protocol",
    day: "Day 20-21",
    videoTitle: "Free CCNA | Spanning Tree Protocol (Part 1 & 2) | Day 20-21 | CCNA 200-301 Complete Course",
    videoUrl: "https://www.youtube.com/watch?v=H8W9oMNSuwo&list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=36",
    embedUrl: "https://www.youtube-nocookie.com/embed/videoseries?list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=36",
    playlistIndex: 36,
  },
  {
    chapterNumber: 15,
    volume: 1,
    volumeChapterNumber: 15,
    moduleId: "v1-ch15-rapid-spanning-tree-protocol",
    day: "Day 22",
    videoTitle: "Free CCNA | Rapid Spanning Tree Protocol | Day 22 | CCNA 200-301 Complete Course",
    videoUrl: "https://www.youtube.com/watch?v=H8W9oMNSuwo&list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=39",
    embedUrl: "https://www.youtube-nocookie.com/embed/videoseries?list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=39",
    playlistIndex: 39,
  },
  {
    chapterNumber: 16,
    volume: 1,
    volumeChapterNumber: 16,
    moduleId: "v1-ch16-etherchannel",
    day: "Day 23",
    videoTitle: "Free CCNA | EtherChannel | Day 23 | CCNA 200-301 Complete Course",
    videoUrl: "https://www.youtube.com/watch?v=H8W9oMNSuwo&list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=41",
    embedUrl: "https://www.youtube-nocookie.com/embed/videoseries?list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=41",
    playlistIndex: 41,
  },
  {
    chapterNumber: 17,
    volume: 1,
    volumeChapterNumber: 17,
    moduleId: "v1-ch17-dynamic-routing",
    day: "Day 24",
    videoTitle: "Free CCNA | OSPF Part 1 | Day 24 | CCNA 200-301 Complete Course",
    videoUrl: "https://www.youtube.com/watch?v=H8W9oMNSuwo&list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=43",
    embedUrl: "https://www.youtube-nocookie.com/embed/videoseries?list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=43",
    playlistIndex: 43,
  },
  {
    chapterNumber: 18,
    volume: 1,
    volumeChapterNumber: 18,
    moduleId: "v1-ch18-open-shortest-path-first",
    day: "Day 25-26",
    videoTitle: "Free CCNA | OSPF Part 2 & 3 | Day 25-26 | CCNA 200-301 Complete Course",
    videoUrl: "https://www.youtube.com/watch?v=H8W9oMNSuwo&list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=45",
    embedUrl: "https://www.youtube-nocookie.com/embed/videoseries?list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=45",
    playlistIndex: 45,
  },
  {
    chapterNumber: 19,
    volume: 1,
    volumeChapterNumber: 19,
    moduleId: "v1-ch19-first-hop-redundancy-protocols",
    day: "Day 27",
    videoTitle: "Free CCNA | First Hop Redundancy Protocols (FHRP) | Day 27 | CCNA 200-301 Complete Course",
    videoUrl: "https://www.youtube.com/watch?v=H8W9oMNSuwo&list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=48",
    embedUrl: "https://www.youtube-nocookie.com/embed/videoseries?list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=48",
    playlistIndex: 48,
  },
  {
    chapterNumber: 20,
    volume: 1,
    volumeChapterNumber: 20,
    moduleId: "v1-ch20-ipv6-addressing",
    day: "Day 28-29",
    videoTitle: "Free CCNA | IPv6 Part 1 & 2 | Day 28-29 | CCNA 200-301 Complete Course",
    videoUrl: "https://www.youtube.com/watch?v=H8W9oMNSuwo&list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=50",
    embedUrl: "https://www.youtube-nocookie.com/embed/videoseries?list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=50",
    playlistIndex: 50,
  },
  {
    chapterNumber: 21,
    volume: 1,
    volumeChapterNumber: 21,
    moduleId: "v1-ch21-ipv6-routing",
    day: "Day 30",
    videoTitle: "Free CCNA | IPv6 Routing | Day 30 | CCNA 200-301 Complete Course",
    videoUrl: "https://www.youtube.com/watch?v=H8W9oMNSuwo&list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=53",
    embedUrl: "https://www.youtube-nocookie.com/embed/videoseries?list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=53",
    playlistIndex: 53,
  },
  {
    chapterNumber: 22,
    volume: 1,
    volumeChapterNumber: 22,
    moduleId: "v1-ch22-transmission-control-protocol-and-user-datagram-protocol",
    day: "Day 31",
    videoTitle: "Free CCNA | Layer 4 Transport Layer | Day 31 | CCNA 200-301 Complete Course",
    videoUrl: "https://www.youtube.com/watch?v=H8W9oMNSuwo&list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=55",
    embedUrl: "https://www.youtube-nocookie.com/embed/videoseries?list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=55",
    playlistIndex: 55,
  },
  {
    chapterNumber: 23,
    volume: 1,
    volumeChapterNumber: 23,
    moduleId: "v1-ch23-standard-access-control-lists",
    day: "Day 32",
    videoTitle: "Free CCNA | Standard IPv4 ACLs | Day 32 | CCNA 200-301 Complete Course",
    videoUrl: "https://www.youtube.com/watch?v=H8W9oMNSuwo&list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=57",
    embedUrl: "https://www.youtube-nocookie.com/embed/videoseries?list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=57",
    playlistIndex: 57,
  },
  {
    chapterNumber: 24,
    volume: 1,
    volumeChapterNumber: 24,
    moduleId: "v1-ch24-extended-access-control-lists",
    day: "Day 33",
    videoTitle: "Free CCNA | Extended IPv4 ACLs | Day 33 | CCNA 200-301 Complete Course",
    videoUrl: "https://www.youtube.com/watch?v=H8W9oMNSuwo&list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=59",
    embedUrl: "https://www.youtube-nocookie.com/embed/videoseries?list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=59",
    playlistIndex: 59,
  },

  // ==========================================
  // VOLUME 2: ADVANCED NETWORKING AND SECURITY (25-49)
  // ==========================================
  {
    chapterNumber: 25,
    volume: 2,
    volumeChapterNumber: 1,
    moduleId: "v2-ch1-cisco-discovery-protocol-and-link-layer-discovery-protocol",
    day: "Day 34",
    videoTitle: "Free CCNA | CDP & LLDP | Day 34 | CCNA 200-301 Complete Course",
    videoUrl: "https://www.youtube.com/watch?v=H8W9oMNSuwo&list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=61",
    embedUrl: "https://www.youtube-nocookie.com/embed/videoseries?list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=61",
    playlistIndex: 61,
  },
  {
    chapterNumber: 26,
    volume: 2,
    volumeChapterNumber: 2,
    moduleId: "v2-ch2-network-time-protocol",
    day: "Day 35",
    videoTitle: "Free CCNA | NTP | Day 35 | CCNA 200-301 Complete Course",
    videoUrl: "https://www.youtube.com/watch?v=H8W9oMNSuwo&list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=63",
    embedUrl: "https://www.youtube-nocookie.com/embed/videoseries?list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=63",
    playlistIndex: 63,
  },
  {
    chapterNumber: 27,
    volume: 2,
    volumeChapterNumber: 3,
    moduleId: "v2-ch3-domain-name-system",
    day: "Day 36",
    videoTitle: "Free CCNA | DNS | Day 36 | CCNA 200-301 Complete Course",
    videoUrl: "https://www.youtube.com/watch?v=H8W9oMNSuwo&list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=65",
    embedUrl: "https://www.youtube-nocookie.com/embed/videoseries?list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=65",
    playlistIndex: 65,
  },
  {
    chapterNumber: 28,
    volume: 2,
    volumeChapterNumber: 4,
    moduleId: "v2-ch4-dynamic-host-configuration-protocol",
    day: "Day 37",
    videoTitle: "Free CCNA | DHCP | Day 37 | CCNA 200-301 Complete Course",
    videoUrl: "https://www.youtube.com/watch?v=H8W9oMNSuwo&list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=67",
    embedUrl: "https://www.youtube-nocookie.com/embed/videoseries?list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=67",
    playlistIndex: 67,
  },
  {
    chapterNumber: 29,
    volume: 2,
    volumeChapterNumber: 5,
    moduleId: "v2-ch5-secure-shell",
    day: "Day 38",
    videoTitle: "Free CCNA | SNMP | Day 38 | CCNA 200-301 Complete Course",
    videoUrl: "https://www.youtube.com/watch?v=H8W9oMNSuwo&list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=69",
    embedUrl: "https://www.youtube-nocookie.com/embed/videoseries?list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=69",
    playlistIndex: 69,
  },
  {
    chapterNumber: 30,
    volume: 2,
    volumeChapterNumber: 6,
    moduleId: "v2-ch6-simple-network-management-protocol",
    day: "Day 39",
    videoTitle: "Free CCNA | Syslog | Day 39 | CCNA 200-301 Complete Course",
    videoUrl: "https://www.youtube.com/watch?v=H8W9oMNSuwo&list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=71",
    embedUrl: "https://www.youtube-nocookie.com/embed/videoseries?list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=71",
    playlistIndex: 71,
  },
  {
    chapterNumber: 31,
    volume: 2,
    volumeChapterNumber: 7,
    moduleId: "v2-ch7-syslog",
    day: "Day 40",
    videoTitle: "Free CCNA | SSH & Telnet | Day 40 | CCNA 200-301 Complete Course",
    videoUrl: "https://www.youtube.com/watch?v=H8W9oMNSuwo&list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=73",
    embedUrl: "https://www.youtube-nocookie.com/embed/videoseries?list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=73",
    playlistIndex: 73,
  },
  {
    chapterNumber: 32,
    volume: 2,
    volumeChapterNumber: 8,
    moduleId: "v2-ch8-trivial-file-transfer-protocol-and-file-transfer-protocol",
    day: "Day 41",
    videoTitle: "Free CCNA | NAT (Part 1) | Day 41 | CCNA 200-301 Complete Course",
    videoUrl: "https://www.youtube.com/watch?v=H8W9oMNSuwo&list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=75",
    embedUrl: "https://www.youtube-nocookie.com/embed/videoseries?list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=75",
    playlistIndex: 75,
  },
  {
    chapterNumber: 33,
    volume: 2,
    volumeChapterNumber: 9,
    moduleId: "v2-ch9-network-address-translation",
    day: "Day 42",
    videoTitle: "Free CCNA | NAT (Part 2) | Day 42 | CCNA 200-301 Complete Course",
    videoUrl: "https://www.youtube.com/watch?v=H8W9oMNSuwo&list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=77",
    embedUrl: "https://www.youtube-nocookie.com/embed/videoseries?list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=77",
    playlistIndex: 77,
  },
  {
    chapterNumber: 34,
    volume: 2,
    volumeChapterNumber: 10,
    moduleId: "v2-ch10-quality-of-service",
    day: "Day 43-44",
    videoTitle: "Free CCNA | Quality of Service (Part 1 & 2) | Day 43-44 | CCNA 200-301 Complete Course",
    videoUrl: "https://www.youtube.com/watch?v=H8W9oMNSuwo&list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=79",
    embedUrl: "https://www.youtube-nocookie.com/embed/videoseries?list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=79",
    playlistIndex: 79,
  },
  {
    chapterNumber: 35,
    volume: 2,
    volumeChapterNumber: 11,
    moduleId: "v2-ch11-security-concepts",
    day: "Day 45",
    videoTitle: "Free CCNA | Security Fundamentals (Part 1) | Day 45 | CCNA 200-301 Complete Course",
    videoUrl: "https://www.youtube.com/watch?v=H8W9oMNSuwo&list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=83",
    embedUrl: "https://www.youtube-nocookie.com/embed/videoseries?list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=83",
    playlistIndex: 83,
  },
  {
    chapterNumber: 36,
    volume: 2,
    volumeChapterNumber: 12,
    moduleId: "v2-ch12-port-security",
    day: "Day 46",
    videoTitle: "Free CCNA | Security Fundamentals (Part 2) | Day 46 | CCNA 200-301 Complete Course",
    videoUrl: "https://www.youtube.com/watch?v=H8W9oMNSuwo&list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=85",
    embedUrl: "https://www.youtube-nocookie.com/embed/videoseries?list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=85",
    playlistIndex: 85,
  },
  {
    chapterNumber: 37,
    volume: 2,
    volumeChapterNumber: 13,
    moduleId: "v2-ch13-dhcp-snooping",
    day: "Day 47",
    videoTitle: "Free CCNA | Port Security | Day 47 | CCNA 200-301 Complete Course",
    videoUrl: "https://www.youtube.com/watch?v=H8W9oMNSuwo&list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=87",
    embedUrl: "https://www.youtube-nocookie.com/embed/videoseries?list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=87",
    playlistIndex: 87,
  },
  {
    chapterNumber: 38,
    volume: 2,
    volumeChapterNumber: 14,
    moduleId: "v2-ch14-dynamic-arp-inspection",
    day: "Day 48-49",
    videoTitle: "Free CCNA | DHCP Snooping & DAI | Day 48-49 | CCNA 200-301 Complete Course",
    videoUrl: "https://www.youtube.com/watch?v=H8W9oMNSuwo&list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=89",
    embedUrl: "https://www.youtube-nocookie.com/embed/videoseries?list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=89",
    playlistIndex: 89,
  },
  {
    chapterNumber: 39,
    volume: 2,
    volumeChapterNumber: 15,
    moduleId: "v2-ch15-lan-architectures",
    day: "Day 50",
    videoTitle: "Free CCNA | Network Architectures | Day 50 | CCNA 200-301 Complete Course",
    videoUrl: "https://www.youtube.com/watch?v=H8W9oMNSuwo&list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=93",
    embedUrl: "https://www.youtube-nocookie.com/embed/videoseries?list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=93",
    playlistIndex: 93,
  },
  {
    chapterNumber: 40,
    volume: 2,
    volumeChapterNumber: 16,
    moduleId: "v2-ch16-wan-architectures",
    day: "Day 51",
    videoTitle: "Free CCNA | Cloud & Virtualization | Day 51 | CCNA 200-301 Complete Course",
    videoUrl: "https://www.youtube.com/watch?v=H8W9oMNSuwo&list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=95",
    embedUrl: "https://www.youtube-nocookie.com/embed/videoseries?list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=95",
    playlistIndex: 95,
  },
  {
    chapterNumber: 41,
    volume: 2,
    volumeChapterNumber: 17,
    moduleId: "v2-ch17-virtualization-and-cloud",
    day: "Day 52",
    videoTitle: "Free CCNA | WAN Concepts | Day 52 | CCNA 200-301 Complete Course",
    videoUrl: "https://www.youtube.com/watch?v=H8W9oMNSuwo&list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=97",
    embedUrl: "https://www.youtube-nocookie.com/embed/videoseries?list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=97",
    playlistIndex: 97,
  },
  {
    chapterNumber: 42,
    volume: 2,
    volumeChapterNumber: 18,
    moduleId: "v2-ch18-wireless-lan-fundamentals",
    day: "Day 53",
    videoTitle: "Free CCNA | Wireless LANs (Part 1) | Day 53 | CCNA 200-301 Complete Course",
    videoUrl: "https://www.youtube.com/watch?v=H8W9oMNSuwo&list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=99",
    embedUrl: "https://www.youtube-nocookie.com/embed/videoseries?list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=99",
    playlistIndex: 99,
  },
  {
    chapterNumber: 43,
    volume: 2,
    volumeChapterNumber: 19,
    moduleId: "v2-ch19-wireless-lan-architectures",
    day: "Day 54",
    videoTitle: "Free CCNA | Wireless LANs (Part 2) | Day 54 | CCNA 200-301 Complete Course",
    videoUrl: "https://www.youtube.com/watch?v=H8W9oMNSuwo&list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=101",
    embedUrl: "https://www.youtube-nocookie.com/embed/videoseries?list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=101",
    playlistIndex: 101,
  },
  {
    chapterNumber: 44,
    volume: 2,
    volumeChapterNumber: 20,
    moduleId: "v2-ch20-wireless-lan-security",
    day: "Day 55",
    videoTitle: "Free CCNA | Wireless Security | Day 55 | CCNA 200-301 Complete Course",
    videoUrl: "https://www.youtube.com/watch?v=H8W9oMNSuwo&list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=103",
    embedUrl: "https://www.youtube-nocookie.com/embed/videoseries?list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=103",
    playlistIndex: 103,
  },
  {
    chapterNumber: 45,
    volume: 2,
    volumeChapterNumber: 21,
    moduleId: "v2-ch21-wireless-lan-configuration",
    day: "Day 55 Lab",
    videoTitle: "Free CCNA | WLC Configuration | Day 55 | CCNA 200-301 Complete Course",
    videoUrl: "https://www.youtube.com/watch?v=H8W9oMNSuwo&list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=104",
    embedUrl: "https://www.youtube-nocookie.com/embed/videoseries?list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=104",
    playlistIndex: 104,
  },
  {
    chapterNumber: 46,
    volume: 2,
    volumeChapterNumber: 22,
    moduleId: "v2-ch22-network-automation",
    day: "Day 56-57",
    videoTitle: "Free CCNA | Network Automation | Day 56-57 | CCNA 200-301 Complete Course",
    videoUrl: "https://www.youtube.com/watch?v=H8W9oMNSuwo&list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=105",
    embedUrl: "https://www.youtube-nocookie.com/embed/videoseries?list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=105",
    playlistIndex: 105,
  },
  {
    chapterNumber: 47,
    volume: 2,
    volumeChapterNumber: 23,
    moduleId: "v2-ch23-rest-apis",
    day: "Day 58",
    videoTitle: "Free CCNA | REST APIs & JSON | Day 58 | CCNA 200-301 Complete Course",
    videoUrl: "https://www.youtube.com/watch?v=H8W9oMNSuwo&list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=108",
    embedUrl: "https://www.youtube-nocookie.com/embed/videoseries?list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=108",
    playlistIndex: 108,
  },
  {
    chapterNumber: 48,
    volume: 2,
    volumeChapterNumber: 24,
    moduleId: "v2-ch24-data-formats",
    day: "Day 59",
    videoTitle: "Free CCNA | Cisco DNA Center & SD-Access | Day 59 | CCNA 200-301 Complete Course",
    videoUrl: "https://www.youtube.com/watch?v=H8W9oMNSuwo&list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=110",
    embedUrl: "https://www.youtube-nocookie.com/embed/videoseries?list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=110",
    playlistIndex: 110,
  },
  {
    chapterNumber: 49,
    volume: 2,
    volumeChapterNumber: 25,
    moduleId: "v2-ch25-ansible-and-terraform",
    day: "Day 60",
    videoTitle: "Free CCNA | Configuration Management | Day 60 | CCNA 200-301 Complete Course",
    videoUrl: "https://www.youtube.com/watch?v=H8W9oMNSuwo&list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=112",
    embedUrl: "https://www.youtube-nocookie.com/embed/videoseries?list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=112",
    playlistIndex: 112,
  },
];

export function getChapterVideo(identifier: string | number): ChapterVideo | undefined {
  if (typeof identifier === "number") {
    return CHAPTER_VIDEOS.find((v) => v.chapterNumber === identifier);
  }

  const raw = identifier.trim().toLowerCase();
  
  // Try matching by exact moduleId
  let found = CHAPTER_VIDEOS.find((v) => v.moduleId.toLowerCase() === raw);
  if (found) return found;

  // Try matching by volume and chapter pattern
  const vMatch = raw.match(/v([12])[-_]ch(\d+)/);
  if (vMatch) {
    const vol = parseInt(vMatch[1], 10);
    const ch = parseInt(vMatch[2], 10);
    found = CHAPTER_VIDEOS.find((v) => v.volume === vol && v.volumeChapterNumber === ch);
    if (found) return found;
  }

  // Try parsing raw number
  const num = parseInt(raw, 10);
  if (!isNaN(num)) {
    return CHAPTER_VIDEOS.find((v) => v.chapterNumber === num);
  }

  return undefined;
}
